version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=storage 
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
      
      
  server:
    build: back-end/
    restart: always
    ports: 
      - 8000:8000
    depends_on: 
      - mongo
    environment:
      - MONGODB_URL=mongodb://user:semantic@mongo:27017/storage
  mongo-monitoring:
    image: mongo-express
    restart: always
    environment:
        - ME_CONFIG_BASICAUTH_PASSWORD=pass
        - ME_CONFIG_BASICAUTH_USERNAME=admin
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    depends_on:
        - mongo
    ports:
        - 8081:8081
  
volumes:
  mongodb_data: