FROM alpine:latest

LABEL image_name="back-end-api"

WORKDIR /back-end 



COPY ./requirements.txt /back-end/

RUN apk update
RUN apk add --no-cache  gcc musl-dev python3 py3-pip
RUN python3 -m venv .venv

RUN source .venv/bin/activate

RUN pip3 install -r requirements.txt --break-system-packages

COPY . /back-end/ 

EXPOSE 8000

CMD ["fastapi", "run", "main.py", "--proxy-headers", "--port", "8000"]